import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';

@Component({
  selector: 'app-tabela',
  templateUrl: './tabela.component.html',
  styleUrls: ['./tabela.component.css']
})
export class TabelaComponent implements AfterViewInit {
  displayedColumns: string[] = ['id', 'name', 'sigla'];
  dataSource: MatTableDataSource<UserData>;

  @ViewChild(MatPaginator) paginator!: MatPaginator;
  @ViewChild(MatSort) sort!: MatSort;

  constructor() {
    const users = Array.from({ length: 100 }, (_, k) => createNewUser(k + 1));
    this.dataSource = new MatTableDataSource(users);
  }

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();
    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
}

function createNewUser(id: number): UserData {
  const sigla = SIGLAS[Math.floor(Math.random() * SIGLAS.length)];
  const name = NAMES[SIGLAS.indexOf(sigla)];

  return {
    id: id.toString(),
    name: name,
    sigla: sigla,
  };
}

const SIGLAS: string[] = [
  'USD',
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'FOK',
  'GBP',
  'GEL',
  'GGP',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'IMP',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JEP',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KID',
  'KMF',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLE',
  'SLL',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TVD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'UYU',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XDR',
  'XOF',
  'XPF',
  'ZAR'
];

const NAMES: string[] = [
  'Dólar Americano',
  'Dirham dos Emirados Árabes Unidos',
  'Afegane Afegão',
  'Lek Albanês',
  'Dram Armênio',
  'Florim das Antilhas Neerlandesas',
  'Kwanza Angolano',
  'Peso Argentino',
  'Dólar Australiano',
  'Florim de Aruba',
  'Manat do Azerbaijão',
  'Marco Convertível da Bósnia e Herzegovina',
  'Dólar de Barbados',
  'Taka de Bangladesh',
  'Lev Búlgaro',
  'Dinar do Bahrein',
  'Franco Burundiano',
  'Dólar das Bermudas',
  'Dólar de Brunei',
  'Boliviano',
  'Real Brasileiro',
  'Dólar das Bahamas',
  'Ngultrum do Butão',
  'Pula do Botswana',
  'Rublo Bielorrusso',
  'Dólar do Belize',
  'Dólar Canadense',
  'Franco Congolês',
  'Franco Suíço',
  'Peso Chileno',
  'Yuan Chinês',
  'Peso Colombiano',
  'Colón da Costa Rica',
  'Peso Cubano',
  'Escudo de Cabo Verde',
  'Coroa Tcheca',
  'Franco do Djibouti',
  'Coroa Dinamarquesa',
  'Peso Dominicano',
  'Dinar Argelino',
  'Libra Egípcia',
  'Nakfa Eritreia',
  'Birr Etíope',
  'Euro',
  'Dólar de Fiji',
  'Libra das Malvinas',
  'Coroa das Ilhas Feroé',
  'Libra Esterlina',
  'Lari Georgiano',
  'Libra de Guernsey',
  'Cedi Ganês',
  'Libra de Gibraltar',
  'Dalasi da Gâmbia',
  'Franco da Guiné',
  'Quetzal Guatemalteco',
  'Dólar da Guiana',
  'Dólar de Hong Kong',
  'Lempira Hondurenha',
  'Kuna Croata',
  'Gourde Haitiano',
  'Florim Húngaro',
  'Rúpia Indonésia',
  'Novo Shekel Israelense',
  'Libra de Isle of Man',
  'Rúpia Indiana',
  'Dinar Iraquiano',
  'Rial Iraniano',
  'Coroa Islandesa',
  'Libra de Jersey',
  'Dólar Jamaicano',
  'Dinar Jordaniano',
  'Iene Japonês',
  'Xelim Queniano',
  'Som Quirguiz',
  'Riel Cambojano',
  'Dólar de Kiribati',
  'Franco das Comores',
  'Won Sul-Coreano',
  'Dinar Kuwaitiano',
  'Dólar das Ilhas Caimão',
  'Tenge Cazaque',
  'Kip Laosiano',
  'Libra Libanesa',
  'Rúpia do Sri Lanka',
  'Dólar Liberiano',
  'Loti do Lesoto',
  'Dinar Líbio',
  'Dirham Marroquino',
  'Leu Moldavo',
  'Ariary Malgaxe',
  'Dinar Macedônio',
  'Kyat de Mianmar',
  'Tugrik Mongol',
  'Pataca de Macau',
  'Ouguiya da Mauritânia',
  'Rúpia de Maurício',
  'Rufiyaa das Maldivas',
  'Kwacha do Malawi',
  'Peso Mexicano',
  'Ringgit Malaio',
  'Metical Moçambicano',
  'Dólar da Namíbia',
  'Naira Nigeriano',
  'Córdoba da Nicarágua',
  'Coroa Norueguesa',
  'Rúpia Nepalesa',
  'Dólar da Nova Zelândia',
  'Rial de Omã',
  'Balboa Panamenho',
  'Sol Peruano',
  'Kina da Papua-Nova Guiné',
  'Peso Filipino',
  'Rúpia Paquistanesa',
  'Złoty Polonês',
  'Guarani Paraguaio',
  'Rial Catariano',
  'Leu Romeno',
  'Dinar Sérvio',
  'Rublo Russo',
  'Franco Ruandês',
  'Rial Saudita',
  'Dólar das Ilhas Salomão',
  'Rupia das Seychelles',
  'Libra Sudanesa',
  'Coroa Sueca',
  'Dólar de Singapura',
  'Libra de Santa Helena',
  'Leone de Serra Leoa',
  'Shilling Somaliano',
  'Dólar do Suriname',
  'Libra Sul-Sudanesa',
  'Dobra de São Tomé e Príncipe',
  'Rupia do Sri Lanka',
  'Franco CFA BCEAO',
  'Dólar do Caribe Oriental',
  'Direitos Especiais de Saque',
  'Franco CFA BEAC',
  'Franco CFP',
  'Rial Iemenita',
  'Rand Sul-Africano',
  'Kwacha Zambiana',
  'Dólar do Zimbábue',
  'Bolívar Venezuelano',
  'Dong Vietnamita',
  'Vatu de Vanuatu',
  'Tala de Samoa',
  'Franco CFA de África Central',
  'Dólar do Caribe Oriental',
  'Direitos Especiais de Saque',
  'Franco CFA de África Central',
  'Franco CFP',
  'Rial Iemenita',
  'Rand Sul-Africano',
  'Kwacha Zambiana',
  'Dólar do Zimbábue',
];

// O resto do código permanece inalterado


export interface UserData {
  id: string;
  name: string;
  sigla: string;
}
